package org.myStudy.entity;

public class Menu extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.PARENT_ID
     *
     * @mbg.generated
     */
    private int parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.URL
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.SERIAL_NUM
     *
     * @mbg.generated
     */
    private int serialNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.STATUS
     *
     * @mbg.generated
     */
    private int status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.NAME
     *
     * @return the value of t_menu.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.NAME
     *
     * @param name the value for t_menu.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.PARENT_ID
     *
     * @return the value of t_menu.PARENT_ID
     *
     * @mbg.generated
     */
    public int getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.PARENT_ID
     *
     * @param parentId the value for t_menu.PARENT_ID
     *
     * @mbg.generated
     */
    public void setParentId(int parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.URL
     *
     * @return the value of t_menu.URL
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.URL
     *
     * @param url the value for t_menu.URL
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.SERIAL_NUM
     *
     * @return the value of t_menu.SERIAL_NUM
     *
     * @mbg.generated
     */
    public int getSerialNum() {
        return serialNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.SERIAL_NUM
     *
     * @param serialNum the value for t_menu.SERIAL_NUM
     *
     * @mbg.generated
     */
    public void setSerialNum(int serialNum) {
        this.serialNum = serialNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.STATUS
     *
     * @return the value of t_menu.STATUS
     *
     * @mbg.generated
     */
    public int getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.STATUS
     *
     * @param status the value for t_menu.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(int status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.REMARK
     *
     * @return the value of t_menu.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.REMARK
     *
     * @param remark the value for t_menu.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}